version: '3.7'

services:
  kotlin-restful-api-postgres:
    container_name: "kotlin-restful-api-postgres"
    image: "postgres:16.4-bullseye"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "restful_api"
